In [1]:
import numpy as np

In [2]:
#输入数据，增加非线性项目 
X = np.array([[1,0,0],
             [1,0,1],
             [1,1,0],
             [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，3行1列 取值范围-1 1
V = np.random.random((3,4))*2 - 1
W = np.random.random((4,1))*2 - 1
     
print(V)
print(W)
#设置学习率
lr = 0.11

def sigmoid(x):
     return 1/(1+np.exp(-x))
def dsigmoid(x):#导数
     return x*(1-x)

def update():
    global X,Y,W,V,lr
    L1 = sigmoid(np.dot(X,V))#(4,4)#输入层传递给隐藏层，输入3个节点，隐藏4个节点
    L2 = sigmoid(np.dot(L1,W))#(4,1)#隐藏层 传递到输出层的值 输出层1个节点
     
    L2_delta = (Y.T - L2)*dsigmoid(L2)#输出层误差值的改变
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)#隐藏层误差值的改变
    W_C = lr*L1.T.dot(L2_delta)#输出层权值的改变
    V_C = lr*X.T.dot(L1_delta)#隐藏层输出的改变
     
    W = W+W_C
    V = V+V_C


[[-0.70750511 -0.71782732 -0.13772678  0.95695262]
 [ 0.36790858  0.75710499  0.97484635 -0.18335048]
 [ 0.02413303  0.04387645 -0.43211159 -0.87478464]]
[[-0.09634867]
 [-0.79485618]
 [-0.96106183]
 [-0.03515903]]


In [3]:
for i in range(20000):
    update()
    if i%500 == 0:
        L1 = sigmoid(np.dot(X,V))#隐藏层(4,4)
        L2 = sigmoid(np.dot(L1,W))#输出层(4,1)
        print("Error:",np.mean(np.abs(Y.T - L2)))

L1 = sigmoid(np.dot(X,V))
L2 = sigmoid(np.dot(L1,W))
print(L2)

def judge(x):
    if x >= 0.5:
        return 1
    else:
        return 0
for i in map(judge,L2):
    print(i)

Error: 0.4989154469848669
Error: 0.4994799982742606
Error: 0.4990785460778756
Error: 0.498419473314511
Error: 0.4968050539942125
Error: 0.49147469904363855
Error: 0.47049201286143716
Error: 0.39562743560739905
Error: 0.250650290213707
Error: 0.16448894224015714
Error: 0.12378670002349193
Error: 0.1010077227023392
Error: 0.08642806766552864
Error: 0.07623081783600003
Error: 0.06865234084867211
Error: 0.06276897960487327
Error: 0.05804976561858717
Error: 0.054167106612613536
Error: 0.05090744050183935
Error: 0.04812528422343939
Error: 0.045717914530666225
Error: 0.04361060972569421
Error: 0.041747636202944916
Error: 0.04008652297070557
Error: 0.03859430083249479
Error: 0.037244959657999385
Error: 0.03601768540952981
Error: 0.03489561047662027
Error: 0.033864910347917006
Error: 0.03291413913200599
Error: 0.03203373305238969
Error: 0.03121563416925199
Error: 0.030453001532706837
Error: 0.029739986843694964
Error: 0.0290715583411425
Error: 0.02844336118185294
Error: 0.027851605743206737
Err