In [8]:
from sklearn import tree
import numpy as np

In [9]:
data = np.genfromtxt("cart.csv",delimiter=",")
x_data = data[1:,1:-1]
y_data = data[1:,-1]
print(x_data)
print(y_data)

[[  1.   0.   1.   0.   0. 125.]
 [  0.   1.   0.   1.   0. 100.]
 [  0.   1.   1.   0.   0.  70.]
 [  1.   0.   0.   1.   0. 120.]
 [  0.   1.   0.   0.   1.  95.]
 [  0.   1.   0.   1.   0.  60.]
 [  1.   0.   0.   0.   1. 220.]
 [  0.   1.   1.   0.   0.  85.]
 [  0.   1.   0.   1.   0.  75.]
 [  0.   1.   1.   0.   0.  90.]]
[0. 0. 0. 0. 1. 0. 0. 1. 0. 1.]


In [10]:
model = tree.DecisionTreeClassifier()
model.fit(x_data,y_data)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
import graphviz#pip install graphviz
# dot_data = tree.export_graphviz(model,
#                                out_file = None,
#                                feature_names=['house_yes','house_no','single','married','divorced','income'],
#                                 class_names = ['no','yes'],
#                                 filled = True,
#                                 rounded = True,
#                                 special_characters = True
#                                )
# graph = graphviz.Source(dot_data)
# graph.render('cart')

ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'cart'], make sure the Graphviz executables are on your systems' PATH