In [15]:
import numpy as np


In [16]:
#输入数据，增加非线性项目  x0 x1 x2 x1*x1 x1*x2 x2*x2 
X = np.array([[1,0,0],
             [1,0,1],
             [1,1,0],
             [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，3行1列 取值范围-1 1
V = np.random.random((3,4))*2 - 1

W = np.random.random((4,1)) *2 - 1
     
print(V)
print(W)
#设置学习率
lr = 0.11


def sigmoid(x):
     return 1/(1+np.exp(-x))
def dsigmoid(x):
     return x*(1-x)

     
def update():
    global X,Y,W,V,lr
    L1 = sigmoid(np.dot(X,V))#(4,4)
    L2 = sigmoid(np.dot(L1,W))#(4,1)
     
    L2_delta = (Y.T - L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)
     
    W = W+W_C
    V = V+V_C


[[-0.45996872 -0.92915072 -0.70939922 -0.45522279]
 [ 0.42833644  0.05669537 -0.53374041  0.99417502]
 [ 0.53434303 -0.45660483 -0.18792995 -0.56758661]]
[[0.32848626]
 [0.87833122]
 [0.82751773]
 [0.43468476]]


In [17]:
for i in range(20000):
    update()
    if i%500 == 0:
        L1 = sigmoid(np.dot(X,V))#隐藏层(4,4)
        L2 = sigmoid(np.dot(L1,W))#输出层(4,1)
        print("Error:",np.mean(np.abs(Y.T - L2)))

L1 = sigmoid(np.dot(X,V))
L2 = sigmoid(np.dot(L1,W))
print(L2)

def judge(x):
    if x >= 0.5:
        return 1
    else:
        return 0
for i in map(judge,L2):
    print(i)

Error: 0.5000760081931656
Error: 0.49980555698390433
Error: 0.4990425248746535
Error: 0.4974882511379079
Error: 0.4918893461942967
Error: 0.4668258057304903
Error: 0.38578803764933106
Error: 0.24279979192716203
Error: 0.1561621893222436
Error: 0.11605495581267941
Error: 0.09413450287184631
Error: 0.0803419413485183
Error: 0.07080851607674946
Error: 0.06378111375786369
Error: 0.05835640419830596
Error: 0.05402204541749111
Error: 0.05046545012567192
Error: 0.04748472700213347
Error: 0.04494340772623007
Error: 0.04274575661603583
Error: 0.04082250970978282
Error: 0.03912223560109852
Error: 0.0376058873484947
Error: 0.03624324689060904
Error: 0.035010534844638334
Error: 0.033888761717167495
Error: 0.032862564450092446
Error: 0.03191936876981828
Error: 0.031048775194347684
Error: 0.030242101680390154
Error: 0.02949203796688061
Error: 0.02879238087399416
Error: 0.02813782915173935
Error: 0.02752382272774838
Error: 0.02694641547048277
Error: 0.026402173541555062
Error: 0.025888093491590988
Er